// ========================
// STATIC DATA — Banaras Ghumo
// ========================

export const navLinks = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
  { href: '/services', label: 'Services' },
  { href: '/tours', label: 'Tours' },
  { href: '/hotels', label: 'Hotels' },
  { href: '/contact', label: 'Contact' },
];

export const stats = [
  { value: '12K+', label: 'Happy Travelers' },
  { value: '200+', label: 'Curated Experiences' },
  { value: '8+', label: 'Years of Legacy' },
  { value: '4.9★', label: 'Average Rating' },
];

export const experiences = [
  {
    id: 1,
    title: 'Sunrise Boat Ride',
    description: 'Witness the first light of dawn paint the ancient ghats in shimmering silver. A private boat glides through sacred waters as the city awakens.',
    duration: '2 Hours',
    price: '₹1,200',
    tag: 'Most Popular',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80',
    icon: '🌅',
  },
  {
    id: 2,
    title: 'Night Ganga Aarti',
    description: 'The most dramatic spiritual spectacle on Earth. Dozens of priests synchronize an ancient fire ritual against the backdrop of glowing lamps.',
    duration: '1.5 Hours',
    price: '₹800',
    tag: 'Must Do',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80',
    icon: '🪔',
  },
  {
    id: 3,
    title: 'Temple Trails',
    description: 'Navigate the labyrinthine lanes of the old city. Discover hidden temples, hear their legends, and touch centuries of living history.',
    duration: '3 Hours',
    price: '₹1,500',
    tag: 'Cultural',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    icon: '🛕',
  },
  {
    id: 4,
    title: 'Street Food Walks',
    description: 'From crispy kachori to silky lassi — guided walks through Banaras\'s most legendary food streets with curated tastings.',
    duration: '2.5 Hours',
    price: '₹999',
    tag: 'Foodie',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80',
    icon: '🍛',
  },
  {
    id: 5,
    title: 'Heritage Photography Tours',
    description: 'Shoot the most cinematic corners of Banaras with a local photographer guide — ghats, alleys, silk weavers, and morning rituals.',
    duration: '4 Hours',
    price: '₹2,200',
    tag: 'Photography',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
    icon: '📸',
  },
  {
    id: 6,
    title: 'Private Cab Tours',
    description: 'Luxury private car tours to Sarnath, Ramnagar Fort, and key landmarks with a knowledgeable local guide and premium vehicle.',
    duration: 'Full Day',
    price: '₹3,500',
    tag: 'Premium',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    icon: '🚗',
  },
];

export const destinations = [
  {
    id: 1,
    name: 'Dashashwamedh Ghat',
    description: 'The grandest ghat — birthplace of the Ganga Aarti ceremony.',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200&q=80',
    category: 'Ghat',
  },
  {
    id: 2,
    name: 'Manikarnika Ghat',
    description: 'The eternal burning ghat — where time itself seems to pause.',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1200&q=80',
    category: 'Ghat',
  },
  {
    id: 3,
    name: 'Kashi Vishwanath Temple',
    description: 'One of India\'s holiest Shiva temples, rebuilt by Marathas in golden splendor.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80',
    category: 'Temple',
  },
  {
    id: 4,
    name: 'Sarnath',
    description: 'Where Buddha first preached. A tranquil garden of ancient stupas and museums.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80',
    category: 'Heritage',
  },
];

export const tourPackages = [
  {
    id: 1,
    title: 'Banaras Classic',
    category: 'Weekend',
    duration: '2D / 1N',
    price: '₹7,999',
    originalPrice: '₹10,500',
    rating: 4.8,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80',
    highlights: ['Ganga Aarti', 'Sunrise Boat', 'Kashi Vishwanath', 'Street Food'],
    badge: 'Best Seller',
    badgeColor: 'cyan',
  },
  {
    id: 2,
    title: 'Spiritual Deep Dive',
    category: 'Extended',
    duration: '3D / 2N',
    price: '₹13,499',
    originalPrice: '₹17,000',
    rating: 4.9,
    reviewCount: 218,
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    highlights: ['All Ghats', 'Sarnath', 'Temple Trail', 'Aarti + Sunrise', 'Heritage Walk'],
    badge: 'Premium',
    badgeColor: 'blue',
  },
  {
    id: 3,
    title: 'Photographer\'s Banaras',
    category: 'Specialty',
    duration: '3D / 2N',
    price: '₹15,999',
    originalPrice: '₹20,000',
    rating: 4.9,
    reviewCount: 87,
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
    highlights: ['Golden Hour Shoots', 'Narrow Lanes', 'Silk Weavers', 'Expert Guide'],
    badge: 'Exclusive',
    badgeColor: 'purple',
  },
  {
    id: 4,
    title: 'Foodie Trail',
    category: 'Specialty',
    duration: '2D / 1N',
    price: '₹8,499',
    originalPrice: '₹11,000',
    rating: 4.7,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80',
    highlights: ['10+ Food Stops', 'Kachori Gali', 'Lassi Shops', 'Sweet Vendors'],
    badge: 'Foodie Pick',
    badgeColor: 'green',
  },
  {
    id: 5,
    title: 'Luxury Banaras',
    category: 'Premium',
    duration: '4D / 3N',
    price: '₹29,999',
    originalPrice: '₹38,000',
    rating: 5.0,
    reviewCount: 64,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    highlights: ['5-Star Stay', 'Private Boat', 'All Experiences', 'Personal Guide', 'Airport Pickup'],
    badge: 'Ultra Luxury',
    badgeColor: 'gold',
  },
  {
    id: 6,
    title: 'Family Heritage',
    category: 'Family',
    duration: '3D / 2N',
    price: '₹18,999',
    originalPrice: '₹24,000',
    rating: 4.8,
    reviewCount: 193,
    image: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=800&q=80',
    highlights: ['Family Boat', 'Sarnath', 'Museum', 'Guided Temples', 'Family Meals'],
    badge: 'Family',
    badgeColor: 'teal',
  },
];

export const hotels = [
  {
    id: 1,
    location: 'Assi Ghat, Varanasi',
    rating: 4.9,
    reviewCount: 312,
    pricePerNight: '₹8,500',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'AC', 'Room Service'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹8,500' },
      { type: 'Premium Room', guests: 3, price: '₹12,000' },
    ],
    badge: 'Riverside View',
  },
  {
    id: 2,
    location: 'Dashashwamedh, Varanasi',
    rating: 4.8,
    reviewCount: 245,
    pricePerNight: '₹6,200',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    amenities: ['Restaurant', 'WiFi', 'AC', 'Rooftop', 'Yoga'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹6,200' },
      { type: 'Premium Room', guests: 3, price: '₹9,500' },
    ],
    badge: 'Heritage View',
  },
  {
    id: 3,
    location: 'Nadesar, Varanasi',
    rating: 5.0,
    reviewCount: 128,
    pricePerNight: '₹22,000',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    amenities: ['Pool', 'Spa', 'Fine Dining', 'WiFi', 'AC', 'Concierge', 'Garden'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹22,000' },
      { type: 'Premium Room', guests: 3, price: '₹32,000' },
    ],
    badge: 'Luxury Estate',
  },
  {
    id: 4,
    location: 'Bhelupur, Varanasi',
    rating: 4.7,
    reviewCount: 189,
    pricePerNight: '₹4,500',
    image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
    amenities: ['Restaurant', 'WiFi', 'AC', 'Gym'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹4,500' },
      { type: 'Premium Room', guests: 3, price: '₹7,000' },
    ],
    badge: 'City Center',
  },
  {
    id: 5,
    location: 'Sarnath, Varanasi',
    rating: 4.8,
    reviewCount: 97,
    pricePerNight: '₹9,800',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'AC', 'Meditation Room'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹9,800' },
      { type: 'Premium Room', guests: 3, price: '₹14,500' },
    ],
    badge: 'Wellness Retreat',
  },
  {
    id: 6,
    location: 'Cantonment, Varanasi',
    rating: 4.6,
    reviewCount: 214,
    pricePerNight: '₹5,500',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c4fe1962?w=800&q=80',
    amenities: ['Restaurant', 'WiFi', 'AC', 'Bar', 'Parking'],
    roomTypes: [
      { type: 'Standard Room', guests: 2, price: '₹5,500' },
      { type: 'Premium Room', guests: 3, price: '₹8,200' },
    ],
    badge: 'Business Friendly',
  },
];

export const services = [
  {
    id: 1,
    title: 'Tour Packages',
    description: 'Handcrafted itineraries from weekend escapes to week-long deep dives into Banaras\'s soul. Each package is uniquely curated.',
    icon: 'Map',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800&q=80',
    features: ['Custom Itineraries', 'Expert Guides', 'Flexible Dates', 'Group & Private'],
  },
  {
    id: 2,
    title: 'Cab Services',
    description: 'Premium AC vehicles with courteous, knowledgeable drivers for city tours, airport transfers, and outstation trips.',
    icon: 'Car',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    features: ['AC Vehicles', '24/7 Availability', 'City & Outstation', 'Airport Pickup'],
  },
  {
    id: 3,
    title: 'Boat Rides',
    description: 'Private and shared boat experiences on the sacred Ganga — from sunrise to starlit nights. Choose your tempo.',
    icon: 'Ship',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80',
    features: ['Private Boats', 'Sunrise Special', 'Evening Aarti', 'Photography Rides'],
  },
  {
    id: 4,
    title: 'Temple Tours',
    description: 'Expert-guided temple circuits covering Kashi Vishwanath, Sankat Mochan, Durga Mandir, and hidden sacred sites.',
    icon: 'Landmark',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    features: ['VIP Access', 'Priest Interactions', 'Historical Stories', 'All Major Temples'],
  },
  {
    id: 5,
    title: 'Hotel Booking',
    description: 'Curated luxury and boutique hotels with Ganga views, rooftop experiences, and seamless service.',
    icon: 'Building',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    features: ['Ganga View Rooms', 'Best Price Guarantee', 'Instant Confirmation', 'Premium Properties'],
  },
  {
    id: 6,
    title: 'Airport Pickup',
    description: 'Smooth, stress-free transfers from Lal Bahadur Shastri Airport to your hotel with meet & greet service.',
    icon: 'Plane',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
    features: ['Meet & Greet', 'Flight Tracking', 'Luxury Vehicles', 'No Hidden Costs'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Arjun Mehta',
    location: 'Mumbai, India',
    rating: 5,
    text: 'Banaras Ghumo turned what could have been a regular pilgrimage into something cinematic. The night aarti experience left me speechless. The team\'s attention to detail is extraordinary.',
    avatar: 'AM',
    trip: 'Spiritual Deep Dive Package',
  },
  {
    id: 2,
    name: 'Sarah Thompson',
    location: 'London, UK',
    rating: 5,
    text: 'As a travel photographer, I\'ve been to 60+ countries. Banaras Ghumo\'s photography tour gave me the most powerful images of my career. The access to hidden lanes was unbelievable.',
    avatar: 'ST',
    trip: 'Photographer\'s Banaras Package',
  },
  {
    id: 3,
    name: 'Priya Sharma',
    location: 'Bangalore, India',
    rating: 5,
    text: 'The sunrise boat ride was everything and more. Waking up at 4:30am was absolutely worth it. The silence, the mist, the glowing city — pure magic. Book it. Now.',
    avatar: 'PS',
    trip: 'Sunrise Boat Experience',
  },
  {
    id: 4,
    name: 'Carlos Rivera',
    location: 'Barcelona, Spain',
    rating: 5,
    text: 'I expected chaos. I found poetry. Banaras Ghumo curated an experience that balanced spirituality with modern comfort perfectly. The hotel they chose had a rooftop view I\'ll never forget.',
    avatar: 'CR',
    trip: 'Luxury Banaras Package',
  },
];

export const faqs = [
  {
    id: 1,
    question: 'When is the best time to visit Banaras?',
    answer: 'October to March is ideal — cool weather, Dev Deepawali in November (an unmissable spectacle), and Mahashivratri in February/March. Summers (April-June) are intense but offers a raw, authentic experience with fewer tourists.',
  },
  {
    id: 2,
    question: 'How do I book a tour package?',
    answer: 'You can book directly through our website, send us a WhatsApp message, or call us. We\'ll confirm your booking within 2 hours and provide a detailed itinerary PDF. Custom packages can be designed within 24 hours.',
  },
  {
    id: 3,
    question: 'Are your boat rides safe?',
    answer: 'Absolutely. All our boats are licensed, regularly maintained, and operated by experienced boatmen who know the Ganga intimately. Life jackets are provided. We adhere to all safety regulations.',
  },
  {
    id: 4,
    question: 'Do you offer custom / private tours?',
    answer: 'Yes — every package can be customized. Prefer a solo sunrise boat with photography? Want a private temple tour with a pandit who speaks English? We can design any experience around your preferences.',
  },
  {
    id: 5,
    question: 'What is the cancellation policy?',
    answer: 'Free cancellation up to 72 hours before the tour. 50% refund between 24–72 hours. No refund within 24 hours (but we can reschedule if needed). Hotel bookings follow the hotel\'s own policy.',
  },
  {
    id: 6,
    question: 'Do you arrange airport pickup?',
    answer: 'Yes! We offer 24/7 airport pickup from Lal Bahadur Shastri Airport (VNS) in premium AC vehicles. Share your flight details during booking and our driver will be there with a nameplate.',
  },
];

export const galleryImages = [
  { id: 1, src: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=600&q=80', alt: 'Ganga Aarti', span: 'row-span-2' },
  { id: 2, src: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&q=80', alt: 'Sunrise Boat Ride', span: '' },
  { id: 3, src: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80', alt: 'Temple Trail', span: '' },
  { id: 4, src: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80', alt: 'Sarnath Heritage', span: 'col-span-2' },
  { id: 5, src: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80', alt: 'Street Food', span: '' },
  { id: 6, src: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80', alt: 'Luxury Hotel', span: '' },
  { id: 7, src: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', alt: 'Private Cab', span: '' },
  { id: 8, src: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80', alt: 'Luxury Suite', span: 'row-span-2' },
];

export const whyChooseUs = [
  { icon: 'Shield', title: 'Verified & Trusted', desc: 'Every experience is vetted. No surprises, no shortcuts.' },
  { icon: 'Users', title: 'Local Experts', desc: 'Born-and-bred Banarasis who know every ghat and gully.' },
  { icon: 'Clock', title: '24/7 Support', desc: 'We\'re on-call before, during, and after your journey.' },
  { icon: 'Star', title: 'Curated Luxury', desc: 'Premium yet approachable experiences for all travelers.' },
  { icon: 'Heart', title: 'Personalized', desc: 'Every itinerary is crafted around your unique story.' },
  { icon: 'Award', title: 'Award Winning', desc: 'Recognized by Times Travel & TripAdvisor as top operator.' },
];
